Repository team-waff1e/Backend, pull requests merged in 2023-10, with the labels that each got.

#1 feat: Add common CrudDao interface
  src/main/java/io/github/teamwaff1e/waffle/domain/dao/CrudDao.java
Labels: feat

#2 doc: Add Issue template, PR template
  .github/BUG_ISSUE_TEMPLATE.md
  .github/FEAT_ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/REFACTOR_ISSUE_TEMPLATE.md
Labels: doc

#3 단일 댓글 CRUD
  src/main/java/io/github/teamwaff1e/waffle/WaffleBackendApplication.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/config/CommentConfig.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/controller/CommentController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dao/CommentDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/converter/CommentToResponseConverter.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/request/CreateCommentRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/request/UpdateCommentRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/entity/Comment.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/repository/CommentRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/service/CommentService.java
  src/main/java/io/github/teamwaff1e/waffle/domain/dao/CrudDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/dto/RequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/dto/ResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/dto/converter/DtoConverter.java
Labels: feat

#8 Docs/convention 추가사항
  .github/ISSUE_TEMPLATE/BUG_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/FEAT_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/REFACTOR_ISSUE_TEMPLATE.md
Labels: doc

#5 Member CRUD
  src/main/java/io/github/teamwaff1e/waffle/WaffleBackendApplication.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/config/MemberConfig.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/controller/MemberController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/dao/MemberDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/dto/converter/MemberToResponseConverter.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/dto/request/CreateMemberRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/dto/request/UpdateMemberRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/dto/response/MemberResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/entity/Member.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/repository/MemberRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/Member/sevice/MemberService.java
  src/test/java/io/github/teamwaff1e/waffle/WaffleBackendApplicationTests.java
  src/test/java/io/github/teamwaff1e/waffle/domain/Member/sevice/MemberServiceTest.java
Labels: feat, BE

#4 단일 Waffle CRUD
  src/main/java/io/github/teamwaff1e/waffle/WaffleBackendApplication.java
  src/main/java/io/github/teamwaff1e/waffle/domain/dao/CrudDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/config/WaffleConfig.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/controller/WaffleController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dao/WaffleDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/converter/WaffleToResponseConverter.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/request/CreateWaffleRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/request/UpdateWaffleRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/WaffleResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/entity/Waffle.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/repository/WaffleRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/service/WaffleService.java
  src/test/java/io/github/teamwaff1e/waffle/domain/waffle/service/WaffleServiceTest.java
Labels: feat, BE

#6 Feature/comment/crud
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/controller/CommentController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dao/CommentDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/converter/CommentToResponseConverter.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/request/CreateCommentRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/request/UpdateCommentRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/entity/Comment.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/repository/CommentRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/service/CommentService.java
  src/main/java/io/github/teamwaff1e/waffle/domain/dao/CrudDao.java
Labels: bugfix, feat, BE

#9 hotfix: hotfix for global CRUD interface changes
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dao/MemberDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/repository/MemberRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dao/WaffleDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/repository/WaffleRepository.java
Labels: hotfix

#10 bugfix: fix bugs on delete feature by pr #6, #9
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dao/WaffleDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/repository/WaffleRepository.java
Labels: bugfix, BE

#12 fix :: change package name and update member DAO/Repo
  src/main/java/io/github/teamwaff1e/waffle/domain/member/controller/MemberController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dao/MemberDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/repository/MemberRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/service/MemberService.java
  src/test/java/io/github/teamwaff1e/waffle/domain/member/service/MemberServiceTest.java
Labels: bugfix, BE

#13 bugfix: fix transactional bugs on like, unlike, update method
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dao/WaffleDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/repository/WaffleRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/service/WaffleService.java
Labels: bugfix, BE

#17 Feat/auth login logout
  build.gradle
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/constant/AuthConstant.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/controller/AuthController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/controlleradvice/AuthControllerAdvice.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/dto/request/LoginRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/repository/AuthRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/service/AuthService.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/vo/AuthVo.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/request/CreateCommentRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/request/UpdateCommentRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dao/MemberDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/request/CreateMemberRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/request/UpdateMemberRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/response/MemberResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/request/CreateWaffleRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/request/UpdateWaffleRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/WaffleResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/global/dto/RequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/global/dto/ResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/global/dto/request/RequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/global/dto/response/ExceptionResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/global/dto/response/ResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/global/exception/ErrorCode.java
  src/main/java/io/github/teamwaff1e/waffle/global/exception/auth/IllegalLoginStateException.java
  src/main/java/io/github/teamwaff1e/waffle/global/exception/auth/LoginFailureException.java
  src/main/java/io/github/teamwaff1e/waffle/global/exception/auth/WAuthException.java
  src/test/java/io/github/teamwaff1e/waffle/domain/auth/service/AuthServiceTest.java
Labels: feat, test, BE

#14 feat: add signup, check duplication of email, nickname feature
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/controller/AuthController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/controlleradvice/AuthControllerAdvice.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/dto/SignupRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/dto/ValidateEmailRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/dto/ValidateNicknameRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/repository/AuthRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/service/AuthService.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dao/MemberDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/service/MemberService.java
  src/main/java/io/github/teamwaff1e/waffle/global/exception/ErrorCode.java
  src/main/java/io/github/teamwaff1e/waffle/global/exception/auth/MemberEmailAlreadyExistsException.java
  src/main/java/io/github/teamwaff1e/waffle/global/exception/auth/MemberNicknameAlreadyExistsException.java
Labels: feat, BE

#19 Feat/auth @login
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/controller/AuthController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/controller/argumentresolver/LoginAuthVoArgumentResolver.java
  src/main/java/io/github/teamwaff1e/waffle/global/annotation/Login.java
  src/main/java/io/github/teamwaff1e/waffle/global/config/WebConfig.java
Labels: feat, BE, refactor

#21 feat: add method tracer TraceAspect
  src/main/java/io/github/teamwaff1e/waffle/global/annotation/Trace.java
  src/main/java/io/github/teamwaff1e/waffle/global/aspect/TraceAspect.java
  src/main/java/io/github/teamwaff1e/waffle/global/config/aspect/AspectConfig.java
Labels: feat

#18 Feature : follow
  src/main/java/io/github/teamwaff1e/waffle/domain/member/controller/MemberController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dao/FollowDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/request/FollowRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/entity/Follow.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/repository/MemberRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/service/MemberService.java
  src/test/java/io/github/teamwaff1e/waffle/domain/member/service/MemberServiceTest.java
Labels: feat, BE
