Repository team-waff1e/Backend, pull requests merged in 2023-11, with the labels that each got.

#23 Feature : add Follow Controller and Valid
  src/main/java/io/github/teamwaff1e/waffle/domain/member/controller/MemberController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dao/FollowDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/request/CreateMemberRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/request/FollowRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/request/UpdateMemberRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/entity/Member.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/service/MemberService.java
  src/main/java/io/github/teamwaff1e/waffle/global/config/WebConfig.java
  src/test/java/io/github/teamwaff1e/waffle/domain/member/service/MemberServiceTest.java
Labels: feat, BE

#26 Feat/comment/crud
  src/main/java/io/github/teamwaff1e/waffle/WaffleBackendApplication.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/controller/CommentController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dao/CommentDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/converter/CommentToResponseConverter.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/request/CreateCommentRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/request/UpdateCommentRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/entity/Comment.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/repository/CommentRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/service/CommentService.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/converter/MemberToResponseConverter.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/request/CreateMemberRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/request/UpdateMemberRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/response/MemberResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/dto/response/OwnerResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/entity/Member.java
  src/main/java/io/github/teamwaff1e/waffle/domain/member/service/MemberService.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/converter/WaffleToResponseConverter.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/WaffleResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/entity/Waffle.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/repository/WaffleRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/service/WaffleService.java
  src/main/java/io/github/teamwaff1e/waffle/global/error/code/ErrorCode.java
  src/main/java/io/github/teamwaff1e/waffle/global/error/controlleradvice/ErrorControllerAdvice.java
  src/main/java/io/github/teamwaff1e/waffle/global/exception/auth/UnauthorizedException.java
Labels: feat, BE, refactor

#27 Feat/comment/crud
  src/main/java/io/github/teamwaff1e/waffle/global/dto/response/ExceptionResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/global/error/code/ErrorCode.java
  src/main/java/io/github/teamwaff1e/waffle/global/error/controlleradvice/ErrorControllerAdvice.java
Labels: feat, BE

#30 [feat, refactor, butfix] readWaffleListByMember api 추가, 특정 사용자의 특정 와플을 조회하는 로직 추가, getWaffleList api refactor, like transactional bug fix
  src/main/java/io/github/teamwaff1e/waffle/domain/likes/dao/LikesDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/likes/repository/LikesRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/controller/WaffleController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dao/WaffleDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/converter/WaffleToResponseConverter.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/request/CreateWaffleRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/request/UpdateWaffleRequestDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/GetWaffleListResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/WaffleListResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/WaffleResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/entity/Waffle.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/repository/WaffleRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/service/WaffleService.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/util/ScrollPaginationCollection.java
Labels: bugfix, feat, BE, refactor

#31 Feat/auth resolve #22 and fix critical bug
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/controller/AuthController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/service/AuthService.java
  src/main/java/io/github/teamwaff1e/waffle/domain/auth/vo/AuthVo.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/controller/CommentController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/comment/service/CommentService.java
  src/main/java/io/github/teamwaff1e/waffle/global/annotation/Login.java
  src/main/java/io/github/teamwaff1e/waffle/global/argumentresolver/LoginAuthVoArgumentResolver.java
  src/main/java/io/github/teamwaff1e/waffle/global/config/WebConfig.java
  src/main/java/io/github/teamwaff1e/waffle/global/interceptor/LoginInterceptor.java
Labels: bugfix, BE, refactor

#32 Feat/waffle/api refactor
  src/main/java/io/github/teamwaff1e/waffle/domain/likes/dao/LikesDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/likes/repository/LikesRepository.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/controller/WaffleController.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dao/WaffleDao.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/dto/response/WaffleResponseDto.java
  src/main/java/io/github/teamwaff1e/waffle/domain/waffle/service/WaffleService.java
Labels: bugfix, feat, BE, refactor
